#prior testing
pr1 <- prior(type.prior=c("gaussian","gamma"),opt.prior=list(c(1,0.01),c(1,0.01)))
pr2 <- prior(type.prior=c("gaussian","unif","gamma","gamma"),opt.prior=list(c(1,0.01),c(0,1),c(2,0.1),c(1,0.01)))
expect_is(pr1,"list")
expect_is(pr2,"list")
pr3 <- prior(type.prior="gaussian",opt.prior=list(c(1,0.01)))
expect_is(pr3,"gaussian.class")
expect_is(pr3,"prior.class")
pr4 <- prior(type.prior="unif",opt.prior=list(c(0,1)))
expect_is(pr4,"unif.class")
expect_is(pr4,"prior.class")
pr5 <- prior(type.prior="gamma",opt.prior=list(c(1,0.1)))
expect_is(pr5,"gamma.class")
expect_is(pr5,"prior.class")
